### PR TITLE
Updating policy name

### PR DESCRIPTION
**Pull request by chelseybeck**
What changed?
- We updated the policy name to replace 'admin' with 'supervisor' and I missed a few places, so that's the only change

The plan should show the 'admin' policy removed and then the new policy (that was applied previously) will be assigned to the group

### CODE REVIEW

**Comment by chelseybeck** [comment]
@freaky4wrld it's okay for you to merge...the previous issue was that the apply step wasn't seeing the plan written as a comment in the pr. I'm wondering if that comment has to be the most recent one...but feel like that shouldn't be the case.

i found these two errors where I didn't change the name, so let's see if it happens again 🤞

**Review by freaky4wrld — APPROVED** [review]
@chelseybeck this looks good, on to merge this!!

PR approved!!

**Comment by freaky4wrld** [comment]
Nope it didn't work!! maybe this prompt from [ChatGPT](https://chat.openai.com/share/a323e21e-1ea5-4c23-83d0-442f3ef71baf) might help you, read the second prompt!!!

**Comment by chelseybeck** [comment]
@freaky4wrld i was able to get it to apply in the latest PR. for whatever reason, I'm having to go back and run the plan action again right before the apply and it works. the error you were seeing was because dflook action didn't detect a plan in the comment - or it wasn't fresh...looking into it

**Pull request merged**
